### ISSUE TITLE
Pogoer in Gobelin team

### ISSUE THREAD

**Issue by sebastienpuigrenier** [wrightomated/blood-bowl-roster#35]
Pogoer in the Gobelin team should be :

const pogoer: Player = {
    id: 32,
    position: 'Pogoer',
    playerStats: [7, 2, 3, 5, 8],
    cost: 75,
    skills: [4, 74, 81],
    primary: ['A'],
    secondary: ['G', 'P', 'S'],
};

**Comment by wrightomated** [comment]
Cheers! Updated the skill categories.
