### ISSUE TITLE
Error message when adding players

### ISSUE THREAD

**Issue by MrCrankshaft** [wrightomated/blood-bowl-roster#48]
Hi,

I attempted to update my Chaos Chosen roster last night by adding a Minotaur as the team's 15th permanent player, but got an ERROR code for "Share URL" and "Export Code."  I got the same ERROR code when I reset and attempted to add a Troll, Ogre or Beastman.  There's enough gold in the treasury, and there are two open roster spots.

Just now, I attempted to add Linemen to both my Wood Elf and Dark Elf rosters... up came ERROR again.  

-MC

**Comment by MrCrankshaft** [comment]
Ah, there's my Minotaur!  Thanks for this, and thanks for designing the roster manager... it's great.

**Comment by wrightomated** [comment]
Thanks heaps for finding the bug!
